---
- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled

- name: Install Nginx
  yum: name=nginx state=latest

- name: Create Nginx Conf Folders
  file: path=/etc/nginx/{{ item }} state=directory owner="{{ nginx_user }}" group="{{ nginx_group}}" mode=755
  with_items:
    - sites-avaliable
    - sites-enable

- name: Copy Nginx Configuration
  template: src=nginxconf.j2 dest=/etc/nginx/nginx.conf
        
- name: Firewall Rules
  command: firewall-cmd --permanent --zone=public --add-service={{ item }}
  with_items:
    - http
    - https
  notify:
    - restart firewall
    - restart nginx
