---
- name: Create a Web Server and ETC
  hosts: all
  become: yes
  become_user: root
  remote_user: vagrant
  vars_files:
    - vars/main.yml
  roles:
    - base
    - role: web
      tags: [web]
    - role: nginx
      tags: [nginx]
