---
- name: Add Group for Nginx
  group: name={{ nginx_group }} state=present

- name: Add User for Nginx
  user: 
    name: "{{ nginx_user }}"

- name: Create the SSH Directory
  file:
    path: /home/sysadm/.ssh/
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    
- name: Download The Public SSH Key From The S3 Bucket
  get_url:
    group: "{{ nginx_group }}"
    owner: "{{ nginx_user }}"
    url: https://s3-us-west-2.amazonaws.com/mberkayk.ssh-key-bucket/authorized_keys
    dest: /home/sysadm/.ssh/

- name: Remove the public SSH key for vagrant user
  file:
    path: /home/vagrant/.ssh/authorized_keys
    state: absent
